server:
  port: 8081
  servlet:
    context-path: /gm

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fhl_gm?useUnicode=true&characterEncoding=utf8&useServerPrepStmts=true&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

